#!/bin/bash

# List of Twitter handles to follow
ACCOUNTS=(
    "SwiftOnSecurity"
    "thegrugq"
    "campuscodi"
    "mikko"
    "hackerfantastic"
    "0xdade"
    "jaysonstreet"
    "lwnnet"
    "torproject"
    "thekitze"
    "geercom"
    "cyb_detective"
    "unix_byte"
    "risc_v"
    "cliffordwolf"
    "kees_cook"
    "bcantrill"
    "ruslanspivak"
    "ferrous_systems"
    "chisel_lang"
    "existentialcoms"
    "daily_wittgenstein"
    "lastpositivist"
    "adamkotsko"
    "MythsModernity"
    "anarchivist"
    "davidgraeber"
    "BuberBot"
    "anarchistagency"
    "crimethinc"
    "enough14"
    "submedia"
    "PMPressOrg"
    "rosenbloommikey"
    "automaton_march"
    "CHRSrobotics"
    "archillect"
    "machinology"
    "benjaminbratton"
    "HenryRollins"
    "scarykidsband"
    "deathtothestock"
    "DecibelMagazine"
    "NoiseNoiseNoise"
    "thehardtimesnews"
    "IronGateStudio"
    "Karnagie"
    "survivalcrafting"
    "LegacyGaming_YT"
    "ark_updates"
    "JBOMidreshet"
    "dkaprah"
    "Hartman_Inst"
    "JewishCurrents"
    "YitzGreenberg"
)

# Loop through accounts and follow them
for account in "${ACCOUNTS[@]}"; do
    echo "Following @$account..."
    t follow "$account"
    sleep 2  # Pause to avoid rate limits
done

echo "All accounts followed!"

